### ISSUE TITLE
test

### ISSUE THREAD

**Issue by alexgruall** [MicrosoftDocs/azure-docs-sdk-go.ru-RU#1]
test

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 37377d96-0f8b-beb6-5919-94b9ea5841ed
* Version Independent ID: c72b5fb1-72e1-8d04-6a1a-9b527128d576
* Content: [Средства для разработчиков, использующих пакет Azure SDK для Go](https://docs.microsoft.com/ru-ru/go/azure/azure-sdk-go-tools)
* Content Source: [azure-go-sdk-conceptual/azure-sdk-go-tools.md](https://github.com/MicrosoftDocs/azure-docs-sdk-go.ru-RU/blob/live-sxs/azure-go-sdk-conceptual/azure-sdk-go-tools.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by CeciAc** [comment]
Hi @alexgrua
I'm closing this issue since no action item is stated
feel free to open a new one if any problem.

Kind regards,
Microsoft DOCS International Team

**Comment by alexgruall** [comment]
Hi Cecilia
Yes, of course. Sorry for that, we are now preparing contest connected with docs here in Russia. 

v-algur@microsoft.com  

Alex Gureev

+79060643927
